# The Docker image that will be used to build your app
image: node:latest
# Functions that should be executed before the build script is run
before_script:
  - npm install
  - npm install airtable
  - npm install axios
pages:
  script:
    - npm run build
    - npm run dev
    artifacts:
        paths:
            - dist/
    rules:
        - if: $CI_COMMIT_BRANCH == "main"

pages:
    stage: deploy
    script:
        - mv dist public
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_BRANCH == "main"

